Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/*'
    - 'config/environments/*'
    - 'config/locales/*'
    - 'config/initializers/devise.rb'
    - 'config/initializers/simple_form.rb'
    - 'config/initializers/new_framework_defaults.rb'
    - 'config/initializers/assets.rb'
    - 'config/initializers/backtrace_silencers.rb'
    - 'config/initializers/rack_mini_profiler.rb'
    - 'config/initializers/wrap_parameters.rb'
    - 'bin/**/*'
    - 'Rakefile'
    - 'node_modules/**/*'
    - 'spec/rails_helper.rb'
